---

## Custom scripts
##
## We deploy the scripts to /usr/local/lib/icinga2-plugins
## because some are run by less-privileged users and might not have access to /etc/icinga2
- file: path="{{ item }}" state=directory owner=root group={{ icinga2_user }} mode=0755
  with_items:
    - /etc/icinga2/conf.d/commands
    - /etc/icinga2/conf.d/services
    - /usr/local/lib/icinga2-plugins

- name: Deploy custom checks
  template:
    src: "usr/local/lib/icinga2-plugins/{{ item }}"
    dest: "/usr/local/lib/icinga2-plugins/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - check_aegir_disk
    - check_aegir_sql
    - check_aegir_civicrm_contacts
    - check_aegir_civicrm_activities
    - check_aegir_civicrm_contributions
    - check_aegir_civicrm_memberships
    - check_aegir_civicrm_mailings
    - check_aegir_civicrm_sms
    - check_aegir_civicrm_cases
    - check_aegir_civicrm_events
    - check_aegir_civicrm_participants
    - check_aegir_civicrm_lastlogin
    - check_backup
    - check_bandwidth
    - check_borg
    - check_civicrm
    - check_cmsversion
    - check_domstats_blockrdbytes
    - check_domstats_blockwrbytes
    - check_domstats_cputime
    - check_domstats_netrxbytes
    - check_domstats_nettxbytes
    - check_emptyheader
    - check_file_content
    - check_memory
    - check_md_raid
    - check_mysqldump-secure
    - check_php_fpm
    - check_smart_attributes
    - check_ufw
    - check_zfs
    - check_zpool
    - restart_service
    - run_aegir_verify
    - run_dist_upgrade

- name: Deploy custom checks extra configs
  template: src="usr/local/lib/icinga2-plugins/{{ item }}" dest="/usr/local/lib/icinga2-plugins/{{ item }}" owner=root group=root mode=0644
  with_items:
    - check_smart_attributes_smartdb.json
  when: "'kvm_servers' in group_names"

- name: Install extra packages for check_smart_attributes
  apt:
    state: present
    install_recommends: no
    name: [
      'smartmontools',
      'libjson-perl',
    ]
  when: "'kvm_servers' in group_names"

# @todo These should only be in ./zones.d/global-templates/commands
# of the icinga2 server. See next task.
- name: Deploy custom checks configurations
  template: src="etc/icinga2/conf.d/commands/{{ item }}.conf" dest="/etc/icinga2/conf.d/commands/{{ item }}.conf" owner=root group=root mode=0644
  with_items:
    - backup
    - bandwidth
    - civicrm
    - cert_expiry
    - cmsversion
    - file_content
    - mem
    - md_raid
    - mysql_uptime
    - ufw
    - zfs
    - zpool
  notify: restart icinga2

- name: Cleanup checks that are now deployed via global-templates
  file:
    path: "/etc/icinga2/conf.d/commands/{{ item }}.conf"
    state: absent
  with_items:
    - aegir_disk
    - aegir_sql
    - mysqldump
  notify: restart icinga2
  tags:
    - icinga2-custom-checks-cleanup

- template: src="etc/sudoers.d/{{ item }}" dest="/etc/sudoers.d/{{ item }}" owner=root group=root mode=0440
  with_items:
    - symbiotic-monitoring
  tags:
    - icinga2-sudo
