---

- name: Force gathering facts for partial ansible runs
  setup:
  tags:
    - packages
    - icinga2
    - icinga2-systemd

- include_tasks:
    file: main-server.yml
    apply:
      tags: icinga2
  when: "'icinga_servers' in group_names"
  tags:
    - icinga2

# - include_tasks:
#     file: main-node.yml
#     apply:
#       tags: icinga2
#   when: "'icinga_servers' not in group_names"
#   tags:
#     - icinga2

# Always deploy custom checks (server and nodes) because the server
# also needs most of those checks locally
- include_tasks:
    file: custom-checks.yml
    apply:
      tags: icinga2-custom-checks
  tags:
    - icinga2-custom-checks

- include_tasks:
    file: main-conf-host.yml
    apply:
      tags: icinga2-conf-host
  tags:
    - never
    - icinga2-conf-host

- include_tasks:
    file: main-conf-host-local.yml
    apply:
      tags: icinga2-conf-host-local
  tags:
    - never
    - icinga2-conf-host-local
