---

# Installs Gitlab using Omnibus packages
# https://about.gitlab.com/downloads/#debian8

- apt: pkg="{{ item }}" state=present
  with_items:
    - debian-archive-keyring
    - apt-transport-https
  tags:
    - gitlab
    - packages

- name: Get the Gitlab repo key
  apt_key: url=https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey state=present
  tags:
    - gitlab
    - packages

- apt_repository:
    repo='deb https://packages.gitlab.com/gitlab/gitlab-ce/debian/ bookworm main'
    state=present
    update_cache=yes
  tags:
    - gitlab
    - packages

- apt: pkg=gitlab-ce state=present
  tags:
    - gitlab
    - packages

# NB: coopsymbiotic/ops#63
# Backup of uploads is done separately using borgmatic
- name: Configure Gitlab cron for backups.
  cron:
    name="gitlab-backup"
    minute="20"
    hour="22"
    job="/opt/gitlab/bin/gitlab-rake gitlab:backup:create CRON=1 SKIP=uploads,builds,tar,repositories"
    cron_file="gitlab-backup"
    user="root"
    state=present
  tags:
    - gitlab
    - gitlab-cron

- name: Gitlab | Deploy fail2ban jail.conf
  template:
    src: "etc/fail2ban/{{ item }}"
    dest: "/etc/fail2ban/{{ item }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - jail.d/gitlab.conf
    - filter.d/nginx-gitlab.conf
  notify: restart fail2ban
  tags:
    - gitlab
    - gitlab-fail2ban

## TODO:
## /etc/gitlab/gitlab.rb
## openssl dhparam -check -5 4096 -out /etc/gitlab/dhparams.4096
