---
- hosts: servers
  become: yes
  roles:
    - common-all
    - icinga2
    - promtail
    - borgmatic
    - mysqlbackup
    - sshuserkeys
    - ufw
    - unattended-upgrades
  tags:
    - base

- hosts: kvm_servers
  become: yes
  roles:
    - kvm-server
  tags:
    - kvm-server

- hosts: aegir_managed
  become: yes
  roles:
    - postfix
    - mariadb
    - php
    - aegir
    - dehydrated
  tags:
    - aegir

- hosts: sql_servers
  become: yes
  roles:
    - mariadb
  tags:
    - mariadb

- hosts: sql_primary_servers
  become: yes
  roles:
    - mariadb
  tags:
    - mariadb

- hosts: sql_replication_servers
  become: yes
  roles:
    - mariadb
  tags:
    - mariadb

- hosts: postfix_servers
  become: yes
  roles:
    - postfix
  tags:
    - postfix

- hosts: backup_servers
  become: yes
  roles:
    - backup-server
  tags:
    - backup-server

- hosts: loki_servers
  become: yes
  roles:
    - loki
  tags:
    - loki

# NB: icinga role intentionally not added because it is already
# running for all servers, so it would make the role run twice.
# unattend-upgrades added because right now it's running on baremetal
- hosts: icinga_servers
  become: yes
  roles:
    - grafana
    - gitlab-runner
    - loki
    - unattended-upgrades
  tags:
    - icinga
    - icinga2

- hosts: gitlab_servers
  become: yes
  roles:
    - gitlab
  tags:
    - gitlab

- hosts: gitlab_runners
  become: yes
  roles:
    - gitlab-runner
  tags:
    - gitlab-runner

- hosts: php_servers
  become: yes
  roles:
    - php
  tags:
    - php

- hosts: buildkit_servers
  become: yes
  roles:
    - buildkit
  tags:
    - buildkit

- hosts: rdiff_backups
  become: yes
  roles:
    - backupninja-rdiff
  tags:
    - backupninja-rdiff

# We still use this wiki, but it is only used to document custom fonts
# - hosts: dokuwiki_instances
#   become: yes
#   roles:
#     - dokuwiki
#   tags:
#     - dokuwiki

- hosts: ufw_managed
  become: yes
  roles:
    - ufw
  tags:
    - ufw

# For hosts not running Aegir
# or with more custom setups
- hosts: dehydrated_manually
  become: yes
  roles:
    - dehydrated
  tags:
    - dehydrated

- hosts: docker_servers
  become: yes
  roles:
    - docker
  tags:
    - docker

- hosts: mattermost_servers
  become: yes
  roles:
    - mattermost
  tags:
    - mattermost
