---

- name: Drupal | Check if CiviCRM is installed (i.e. has civicrm.settings.php)
  stat:
    path: "{{ site_path }}/civicrm.settings.php"
  register: civicrm_is_active

- name: Drupal | Run civicrm database upgrades
  become_user: aegir
  shell:
    chdir: "{{ site_path }}"
    cmd: cv --no-interaction --out=json-pretty upgrade:db
  when: civicrm_is_active.stat.exists

- name: Drupal | Update logging schema as a precaution after upgrades
  become_user: aegir
  shell:
    chdir: "{{ site_path }}"
    cmd: cv php:script /var/aegir/hostmaster/profiles/hostmaster/modules/aegir/hosting_civicrm/cv/schemalog.php
  ignore_errors: yes
  when: civicrm_is_active.stat.exists

- name: Drupal | Run civicrm extension database upgrades
  become_user: aegir
  shell:
    chdir: "{{ site_path }}"
    cmd: cv api Extension.upgrade
  when: civicrm_is_active.stat.exists

- include_tasks: drupal-civicrm-cron.yml
  when: "'civicrm_sites' in group_names"
  tags:
    - civicrm-sites-cron-drupal

- include_tasks: drupal-core-cron.yml
