#!/bin/bash

# {{ ansible_managed }}

# Outputs the contents of the Aegir usage.log in a way that Icinga2
# can fetch the metrics so that they can be fed to Graphite/Grafana.
# It does not do any quota checks at the moment.

# Ex input: 
# aegir,example.org,CiviPaymentProcessors:Stripe

# Extract the production sites (grep -v skip)
# .. keep only CiviPaymentProcessors entries
# and remove the 'aegir,' prefix (cut ..)
sites=$(cat /var/log/aegir/usage.log | grep -v ',skip$' | grep CiviPaymentProcessors | cut -f 2- -d ',')

echo -n "AEGIR CiviCRM Payment Processors OK |"

while read -r line; do
  # Match the first field
  site_name=${line%%,*}
  site_name=${site_name//./_}

  # Match the last field
  pp=${line##*:}

  # Since Icinga does not like strings, we only return
  # the count of enabled processors.
  echo -n " $site_name="
  echo -n ${pp} | awk -F'+' '{printf NF-1}'
  echo -n ";"
done <<< "$sites"
