---

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - postfix
  tags:
    - packages
    - postfix
    - opendkim
    - opendkim-tools
    - ssl-cert # for snakeoil cert

- name: Set the postfix mailname (and chmod it to be public, required by Aegir).
  template:
    src: "etc/mailname"
    dest: "/etc/mailname"
    owner: "root"
    group: "root"
    mode: 0644
  notify: restart postfix
  tags:
    - postfix

- name: Deploy the postfix main.cf configuration.
  template:
    src: "etc/postfix/main.cf"
    dest: "/etc/postfix/main.cf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: restart postfix
  tags:
    - postfix

- name: Override the systemd service unit
  template:
    src: "lib/systemd/system/opendkim.service"
    dest: "/etc/systemd/system/opendkim.service"
    owner: "root"
    group: "root"
    mode: 0644
  notify: reload systemd
  tags:
    - postfix
    - postfix-opendkim
