---
# Installs MariaDB using third-party packages for more version flexibility
# Assumes Debian stable

- name: Force gathering facts for partial ansible runs
  setup:
  tags:
    - mariadb-settings

# https://github.com/gaspaio/ansible-devbox/blob/master/roles/mysql/tasks/server.yml
# Install server using a preseed file to set the root password
- name: Check for previous MySQL installation
  stat:
    path: /usr/sbin/mysqld
  register: mysqld_exists

- apt:
    name: [
      "mariadb-client",
      "mariadb-server",
      # For MySQL health monitoring
      "libdbd-mysql-perl"
    ]
    state: present
    install_recommends: no
  tags:
    - packages

- include: settings-mysql.yml
  tags:
    - mariadb-settings
