---

# Firewall (iptables)
- name: ufw | Install ufw
  apt: name=ufw state=present
- apt:
    name: [
      "ufw",
      "fail2ban",
      "python3-systemd",
    ]
    state: present
    install_recommends: no
  tags:
    - ufw
    - ufw-packages
    - ufw-fail2ban

- name: Set UFW default forward policy to ACCEPT for KVM servers
  ufw:
    default: allow
    direction: routed
  when: "'kvm_servers' in group_names"
  tags:
    - ufw

- name: Remove old ssh allow-all rule
  ufw: proto=tcp port=22 rule=allow delete=yes
  tags:
    - ufw

- name: Allow ssh on IPv4
  ufw: proto=tcp port=22 src="0.0.0.0/0" rule=allow
  when: ufw_ipv4_allow_ssh == true
  tags:
    - ufw

- name: Allow ssh on IPv6 only
  ufw: proto=tcp port=22 src="::/0" rule=allow
  when: ufw_ipv6_allow_ssh == true
  tags:
    - ufw

- name: Allow http
  ufw: proto=tcp port=80 rule=allow
  when: ufw_allow_http == true
  tags:
    - ufw

- name: Allow https
  ufw: proto=tcp port=443 rule=allow
  when: ufw_allow_https == true
  tags:
    - ufw

- name: Remove http
  ufw: proto=tcp port=80 rule=allow delete=yes
  when: ufw_allow_http == false
  tags:
    - ufw

- name: Remove https
  ufw: proto=tcp port=443 rule=allow delete=yes
  when: ufw_allow_https == false
  tags:
    - ufw

- name: Allow access to icinga2 5665 from icinga2 servers
  ufw: proto=tcp port=5665 rule=allow src="{{ item }}"
  with_items: "{{ ufw_icinga_allow_src }}"
  tags:
    - ufw
    - ufw-icinga

# UFW per-host exceptions
# see https://github.com/ansible/ansible/issues/10047 for why the weird default.
- ufw: proto="{{ item.value.proto }}" port="{{ item.value.port }}" src="{{ item.value.src }}" rule="{{ item.value.rule }}"
  with_dict: "{{ ufw_extra | default({}) }}"
  tags:
    - ufw
    - ufw-extra

# More per-host extensions (because sometimes we have all/group rules, and then per-host rules)
- ufw: proto="{{ item.value.proto }}" port="{{ item.value.port }}" src="{{ item.value.src }}" rule="{{ item.value.rule }}"
  with_dict: "{{ ufw_extra2 | default({}) }}"
  tags:
    - ufw
    - ufw-extra2

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny
  tags:
    - ufw

- name: Disable logging
  ufw:
    logging: off
  tags:
    - ufw

- name: Restart ufw
  service: name=ufw state=restarted
  tags:
    - ufw

- name: ufw | Deploy fail2ban jail.conf
  template: src=etc/fail2ban/jail.conf dest=/etc/fail2ban/jail.conf owner=root group=root mode=0644
  tags:
    - ufw
    - ufw-fail2ban

- name: Deploy fail2ban configurations for CiviCRM
  template:
    src: "etc/fail2ban/{{ item }}"
    dest: "/etc/fail2ban/{{ item }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - fail2ban.d/symbiotic-ipv6.conf
    - jail.d/civicrm.conf
    - filter.d/nginx-civicrm.conf
    - filter.d/phperror-civicrm.conf
    - action.d/ufw.conf
  when: "'aegir_managed' in group_names"
  notify: restart fail2ban
  tags:
    - ufw
    - ufw-fail2ban

# see https://github.com/fail2ban/fail2ban/issues/3292
- name: Fix fail2ban sshd config for Debian
  lineinfile:
    path: /etc/fail2ban/paths-debian.conf
    regexp: '^sshd_backend = systemd'
    line: 'sshd_backend = systemd'
  notify: restart fail2ban
  tags:
    - ufw-fail2ban
