---

- name: Force gathering facts for partial ansible runs
  setup:
  tags:
    - packages
    - borgmatic
    - borgmatic-confs

- name: borgmatic | Install python3 requirements and borgbackup
  apt:
    state: present
    name: [
      'borgbackup',
      'borgmatic',
      # required for the monitoring scripts
      'jq',
    ]
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags:
    - borgmatic
    - packages

- name: Create the borgmatic config directory
  file:
    path: "/etc/borgmatic"
    state: directory
    owner: "root"
    group: "root"
    mode: 0700
  tags:
    - borgmatic
    - borgmatic-confs

- name: Deploy the main borgmatic configuration file.
  template:
    src: "etc/borgmatic/config.yaml"
    dest: "/etc/borgmatic/config.yaml"
    owner: "root"
    group: "root"
    mode: 0600
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'trixie'
  tags:
    - borgmatic
    - borgmatic-confs

- name: Deploy the main borgmatic configuration file (legacy).
  template:
    src: "etc/borgmatic/config-legacy.yaml"
    dest: "/etc/borgmatic/config.yaml"
    owner: "root"
    group: "root"
    mode: 0600
  when: ansible_distribution_release != 'trixie'
  tags:
    - borgmatic
    - borgmatic-confs

# Configure cron path - now provided by the borgmatic Debian package
# - name: Configure cron PATH for borgmatic.
#   cronvar:
#     name: "PATH"
#     value: "/usr/bin:/bin"
#     cron_file: "borgmatic"
#   tags:
#     - borgmatic
#     - borgmatic-confs
#     - borgmatic-cron

# Run cron randomly between 23:00 AND 03:59
# - name: borgmatic | Configure cron
#   cron:
#     name="borgmatic"
#     minute="{{ 60 | random }}"
#     hour="{{ ['23','0','1','2','3'] | random }}"
#     job="/usr/bin/borgmatic --verbosity 0"
#     cron_file="borgmatic"
#     user="root"
#     state=present
#   tags:
#     - borgmatic
#     - borgmatic-confs
#     - borgmatic-cron

- name: Make sure that the old borgmatic cron is absent
  file: path="/etc/cron.d/borgmatic" state=absent
  tags:
    - borgmatic
    - borgmatic-confs
    - borgmatic-cron

- name: Make sure that the old mysqlbackup cron is absent
  file: path="/etc/cron.d/mysqlbackup" state=absent
  tags:
    - borgmatic
    - borgmatic-confs
    - borgmatic-cron

- name: borgmatic | Generate an ssh key if necessary for root
  user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  tags:
    - borgmatic
    - borgmatic-ssh

- name: borgmatic | Add backup server to known_hosts
  shell: ssh-keyscan -H {{ borgmatic_backupserver }} >> ~/.ssh/known_hosts
  tags:
    - borgmatic
    - borgmatic-ssh

- name: borgmatic | Fetch the root public ssh key
  command: cat /root/.ssh/id_rsa.pub
  register: root_pub_key
  tags:
    - borgmatic
    - borgmatic-ssh

- name: borgmatic | Create the backup user on backup server
  delegate_to: "{{ borgmatic_backupserver }}"
  user: name="backups-{{ inventory_hostname_short }}" home="{{ borgmatic_server_basedir }}/{{ inventory_hostname }}"
  tags:
    - borgmatic
    - borgmatic-ssh

- name: borgmatic | Update backup server home directory permissions
  delegate_to: "{{ borgmatic_backupserver }}"
  file:
    path="{{ borgmatic_server_basedir }}/{{ inventory_hostname }}"
    state=directory
    owner="backups-{{ inventory_hostname_short }}"
    group="backups-{{ inventory_hostname_short }}"
    mode=0700
  tags:
    - borgmatic
    - borgmatic-ssh

- name: borgmatic | Create the backup directory on backup server
  delegate_to: "{{ borgmatic_backupserver }}"
  file:
    path="{{ borgmatic_server_basedir }}/{{ inventory_hostname }}/borg"
    state=directory
    owner="backups-{{ inventory_hostname_short }}"
    group="backups-{{ inventory_hostname_short }}"
    mode=0700
  tags:
    - borgmatic
    - borgmatic-ssh

- name: borgmatic | Add the public ssh key to backup account on the backup server
  delegate_to: "{{ borgmatic_backupserver }}"
  authorized_key:
    user: "backups-{{ inventory_hostname_short }}"
    key: "{{root_pub_key.stdout}}"
    key_options: "command=\"borg serve --restrict-to-path {{ borgmatic_server_basedir }}/{{ inventory_hostname }}/borg/\",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc"
  tags:
    - borgmatic
    - borgmatic-ssh

- name: borgmatic | Add extra ssh keys to the backup server if defined
  delegate_to: "{{ borgmatic_backupserver }}"
  authorized_key: user="backups-{{ inventory_hostname_short }}" key="{{ lookup('file', item) }}"
  with_items: "{{ borgmatic_extra_sshkeys }}"
  when: borgmatic_extra_sshkeys is defined and borgmatic_extra_sshkeys
  tags:
    - borgmatic
    - borgmatic-ssh
    - borgmatic-ssh-extra

- name: borgmatic | Check if the repository has been initialized
  stat:
    path: "/root/.borgmatic-init-{{ borgmatic_backupserver }}"
  register: borgmatic_init_exists
  tags:
    - borgmatic
    - borgmatic-init

- name: borgmatic | Initialize the repository
  shell: "env BORG_PASSPHRASE='{{ borgmatic_passphrase }}' borgmatic init -e repokey"
  when: not borgmatic_init_exists.stat.exists
  tags:
    - borgmatic
    - borgmatic-init

- name: borgmatic | Touch the init file
  file:
    path: "/root/.borgmatic-init-{{ borgmatic_backupserver }}"
    state: touch
    mode: 0600
  when: not borgmatic_init_exists.stat.exists
  tags:
    - borgmatic
    - borgmatic-init

- name: sudo | Deploy sudoers file for restoring backups
  template:
    src: "etc/sudoers.d/symbiotic-borg"
    dest: "/etc/sudoers.d/symbiotic-borg"
    owner: root
    group: root
    mode: 0440
  tags:
    - borgmatic
    - borgmatic-sudoers

- name: sudo | Deploy our wrapper scripts for mounting and unmounting
  template:
    src: "usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - borg-mount
    - borg-umount
  tags:
    - borgmatic
    - borgmatic-sudoers
