# We use third-party packages so that we can be sure to have the same NodeJS version
# on all servers, regardless of which Debian version they are running.

# Based on: https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/setup-Debian.yml

# Cleanup old versions
- file: path=/etc/apt/sources.list.d/deb_nodesource_com_node_10_x.list state=absent
- file: path=/etc/apt/sources.list.d/deb_nodesource_com_node_12_x.list state=absent
- file: path=/etc/apt/sources.list.d/deb_nodesource_com_node_14_x.list state=absent
- file: path=/etc/apt/sources.list.d/deb_nodesource_com_node_16_x.list state=absent
- file: path=/etc/apt/sources.list.d/deb_nodesource_com_node_18_x.list state=absent
- file: path=/etc/apt/sources.list.d/deb_nodesource_com_node_20_x.list state=absent
- file: path=/etc/apt/sources.list.d/deb_nodesource_com_node_22_x.list state=absent

# @todo This should be in the common-all, but we need it for upgrades too
- name: Install python-debian
  apt:
    name: python3-debian
    state: present
    install_recommends: no

- name: Download NodeSource's signing key.
  # NodeSource's web server discriminates the User-Agent used by the deb822_repository module.
  # https://github.com/nodesource/distributions/issues/1723
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/signing-key-nodesource-repo.asc
    owner: root
    group: root
    mode: '0444'
  register: node_signing_key

- name: Add NodeSource repositories for Node.js.
  ansible.builtin.deb822_repository:
    name: nodesource
    uris: "https://deb.nodesource.com/node_{{ nodejs_version }}"
    types: deb
    suites: nodistro
    components: main
    signed_by: "{{ node_signing_key.dest }}"
    state: present
  register: node_repo

- name: Run apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Install nodejs
  apt:
    name: nodejs
    state: present
    install_recommends: no

# This isn't great, because it installs in /usr/bin/bower (not /usr/local/bin).
- name: Install bower using npm
  npm: name=bower global=yes
