---

- name: ssh | Create the .ssh directory for the Aegir user
  file: path=/var/aegir/.ssh state=directory mode="{{ aegir_ssh_dir_permission }}" owner=aegir group="{{ aegir_ssh_dir_group }}"
  tags:
    - aegir-ssh
    - aegir-civicrm-platform

- name: ssh | Copy the ssh platform pub key
  copy: src="{{ inventory_dir }}/files/sshkeys/aegir/id_rsa_platforms.pub" dest=/var/aegir/.ssh/id_rsa_platforms.pub owner="aegir" group="aegir" mode=0600
  tags:
    - aegir-ssh
    - aegir-civicrm-platform

- name: ssh | Copy the ssh platform priv key
  copy: src="{{ inventory_dir }}/files/sshkeys/aegir/id_rsa_platforms" dest=/var/aegir/.ssh/id_rsa_platforms owner="aegir" group="aegir" mode=0600
  tags:
    - aegir-ssh
    - aegir-civicrm-platform

- name: ssh | Create the .ssh/config file if necessary
  file: path=/var/aegir/.ssh/config state=touch mode=0600 owner=aegir group=aegir
  tags:
    - aegir-ssh
    - aegir-civicrm-platform

- name: ssh | Copy ssh config for this key
  blockinfile:
    dest: /var/aegir/.ssh/config
    block: |
      Host git-alt.symbiotic.coop
        IdentityFile /var/aegir/.ssh/id_rsa_platforms
      Host lab-platform-key.symbiotic.coop
        HostName lab.symbiotic.coop
        IdentityFile /var/aegir/.ssh/id_rsa_platforms
  tags:
    - aegir-ssh
    - aegir-civicrm-platform

- name: ssh | Add git ssh host key fingerprints to known_hosts to avoid prompts
  known_hosts:
    path='/etc/ssh/ssh_known_hosts'
    host='{{ item }}'
    key="{{ lookup('pipe', 'ssh-keyscan ' + item) }}"
  with_items:
    - lab.symbiotic.coop
    - lab-platform-key.symbiotic.coop
  tags:
    - aegir-ssh
    - aegir-civicrm-platform

- name: platform | Clone the Symbiotic platform
  become_user: aegir
  git: repo=git@lab-platform-key.symbiotic.coop:coopsymbiotic/symbiotic-platform-d{{ aegir_platform_drupal_version }}-civicrm.git
       recursive=yes
       force=yes
       version=master
       dest="/var/aegir/platforms/civicrm-d{{ aegir_platform_drupal_version }}"
       update=yes
  tags:
    - aegir-civicrm-platform
