#!/bin/bash

# {{ ansible_managed }}

# Monitor libvirt dom cpu.time

set -e

mkdir -p /var/lib/icinga2/domstats
sudo /usr/bin/virsh domstats | awk 'BEGIN {DOMAIN=""} match($0, "^Domain: (.*)") {DOMAIN=$2;} { print DOMAIN, $1 }' | grep cpu.time | sed  "s/'//g" | sed 's/ cpu.time//' > /var/lib/icinga2/domstats/cputime.new
stats=$(paste /var/lib/icinga2/domstats/cputime /var/lib/icinga2/domstats/cputime.new | awk -F'[= ]' '{print $1 "=" ($3 - $2) }')
mv /var/lib/icinga2/domstats/cputime.new /var/lib/icinga2/domstats/cputime

echo -n "Libvirt cpu.time OK |"

while read -r line; do
  echo -n " $line;"
done <<< "$stats"
