borgmatic_backupserver: backupserver.example.org
borgmatic_retention_daily: 14
borgmatic_retention_weekly: 3
borgmatic_retention_monthly: 4
borgmatic_passphrase: storedelsewhere

# ssh username
borgmatic_user: "backups-{{ inventory_hostname_short }}"

# Base directory where backups are stored, on the backup server
borgmatic_server_basedir: /backup

# On rsync.net, set to "borg1"
borgmatic_remote_path: ""

# Require a password to run the sudo command
# alternative password-less: "NOPASSWD:"
borgmatic_sudorule: "(root)"

# To run commands after the completion of a backup
# borgmatic_after_backup:
# - ls
