---

# Forcing ansible.posix:1.6.1 is required when using Ansible 2.14, which is what Debian 12/bookworm ships
- name: Install Ansible modules
  shell: ansible-galaxy collection install community.mysql ansible.posix:1.6.1

- name: Download aegir-ansible-playbooks
  git:
    repo: https://github.com/coopsymbiotic/aegir-ansible-playbooks.git
    version: master
    dest: /usr/local/aegir-ansible-playbooks
    update: yes

- name: Run the Aegir-on-Backdrop installation
  shell:
    chdir: "/usr/local/aegir-ansible-playbooks"
    cmd: "ansible-playbook ./aegir/admin/install.yml"
