---

- name: Force gathering facts for partial ansible runs
  setup:
  tags:
    - packages
    - icinga2

# Now using standard Debian packages, not worth the hassle
# Not accessible on ipv6-only hosts, so in those situations we use the standard Debian packages
# - name: Get Icinga Apt Key
#   apt_key:
#     url="https://packages.icinga.com/icinga.key"
#     state=present
#   when: preseed_ipv4_address is defined
#   tags:
#     - packages
#     - icinga2
#
# - name: Configure Icinga Apt Repo
#   apt_repository:
#     repo="deb https://packages.icinga.com/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main"
#     update_cache=yes
#     state=present
#   when: preseed_ipv4_address is defined
#   tags:
#     - packages
#     - icinga2

- include_tasks: main-server.yml
  when: "'icinga_servers' in group_names"
  tags:
    - icinga2

- include_tasks: main-node.yml
  when: "'icinga_servers' not in group_names"
  tags:
    - icinga2

# Always deploy custom checks (server and nodes) because the server
# also needs most of those checks locally
- include_tasks: custom-checks.yml
  tags:
    - icinga2-custom-checks

- include_tasks: main-conf-host.yml
  tags:
    - never
    - icinga2-conf-host

- include_tasks: main-conf-host-local.yml
  tags:
    - never
    - icinga2-conf-host-local
