---
- name: Reload apache2
  become: true
  service:
    name: apache2
    state: reloaded
    enabled: true

- name: Restart apache2
  become: true
  service:
    name: apache2
    state: restarted
    enabled: true
